### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by baentsch**
Implements #19

### CODE REVIEW

**Comment by gregorseiler** [comment]
Thank you for this pull request adding support for CMake. I'm happy to take it but could you please first change the following. The fips202 implementation in the avx2 version of Dilithium is identical to the one in the ref version. Therefore it lives in the same namespace and the files are actually just symlinks. I don't want to change this. If some downstream library wants to provide two separate implementations and put one into the _avx2 namespace then they can easily do this locally.

**Comment by baentsch** [comment]
May I ask what the reason is for your statement
> I don't want to change this.

My rationale for the proposed change: Separating the fips202 namespacing between avx2 and ref enables building _one_ dilithium library with different compile options set in ref and avx2, e.g., to facilitate building _one_ portable but still performant library (i.e., using `-O3` but NO `-mnative` in 'ref' and `-mavx2` in 'avx2') not only downstream but already here.

Admittedly, dilithium as it is set up right now does not provide a useable API for library consumers. 
So, maybe your goal is to _not_ provide a library for actual, immediate consumption/usage? Can you please confirm, e.g., whether you want users to ever be able to `#include/-ldilithium` from this code base?

**Comment by gregorseiler** [comment]
On 11.06.20 15:21, Michael Baentsch wrote:
> May I ask what the reason is for your statement
> 
>     I don't want to change this.

It is much easier for us to maintain the code base if the ref and avx2 
implementations are as close to each other as possible. I actually plan 
to factor out more of the code that is shared between the two 
implementations than just the shake code.

> My rationale for the proposed change: Separating the fips202 namespacing 
> between avx2 and ref enables building /one/ dilithium library with 
> different compile options set in ref and avx2, e.g., to facilitate 
> building /one/ portable but still performant library (i.e., using |-O3| 
> but NO |-mnative| in 'ref' and |-mavx2| in 'avx2') not only downstream 
> but already here.

I don't see why you shouldn't be able to do this right now. The whole 
point of our namespacing support is to make exactly this possible. But 
since there is essentially no point in compiling fips202.c with avx2 
instruction support enabled, your Dilithium shared library should only 
include one compiled version of fips202.c. This is then to be used by 
all Dilithium implementations for all parameter sets and no matter if 
they make use of AVX2 instructions or not.

So, concretely, if you run 'make shared' in ref/ and avx2/ now, you get 
shared libraries

   libpqcrystals_dilithiumALG_ref.so

for all parameter sets ALG in {2,2aes,3,3aes,4,4aes}, and similarly

   libpqcrystals_dilithiumALG_avx2.so

also for all parameter sets. But you only get one library

   libpqcrystals_fips202_ref.so

The last library from the ref directory provides all the SHAKE functions 
that are called from the functions in the dilithium*_ref libraries _as 
well as_ from the functions in the dilithium*_avx2 libraries. You can 
now link some program against all these libraries and have access to all 
Dilithium implementations, with avx2 instructions and without. And if 
you want you can very easily compile everything into one single library 
dilithium.so.

Of course in the long run in an actual crypto library you probably don't 
want that Dilithium has its own SHAKE implementation. But the way it is 
now is still better than having multiple instances of exactly the same code.

On the other hand if in your library you do want to have a separate set 
of the SHAKE functions in the AVX2 namespace, then you can also very 
easily do this by changing just one line of code. So, as you have done 
in your pull request, you just copy fips202.c/h and change

   #define FIPS202_NAMESPACE(s) pqcrystals_fips202_ref##s

to

   #define FIPS202_NAMESPACE(s) pqcrystals_fips202_avx2##s

The avx2 Dilithium implementations will then automatically call your 
separate SHAKE functions.

> Admittedly, dilithium as it is set up right now does not provide a 
> useable API for library consumers.
> So, maybe your goal is to /not/ provide a library for actual, immediate 
> consumption/usage? Can you please confirm, e.g., whether you want users 
> to ever be able to |#include/-ldilithium| from this code base?

I fail to see why you get to this conclusion. I have actually put a lot 
of work into making it easier for libraries to take up the code.

Cheers,
Gregor

**Comment by baentsch** [comment]
> It is much easier for us to maintain the code base if the ref and avx2
implementations are as close to each other as possible. I actually plan
to factor out more of the code that is shared between the two
implementations than just the shake code.

That's great to hear and will be greatly welcomed.

>I fail to see why you get to this conclusion. I have actually put a lot
of work into making it easier for libraries to take up the code.

I think we need to talk in person as I feel we have a significant disconnect here.
Until we find time to do that, let's continue the GitHub conversation starting by considering what _my goal_ for the cmake build was: It was to have _one_ (either static or shared) library containing all dilithium variants (portable _and_ fast), ready to be consumed/linked to, not several separate files. All the work you did is the basis of what the cmake build infrastructure takes in. All future work that you mention will make this smaller and more efficient. 
However, I wonder what the header (should) look like that immediate consumers of this library (if it is a desirable goal for us to create that) shall include, enabling them to utilize dilithium 2, 3, or 4... Or is your assumption users must use/link to different libraries and include different headers for different dilithium variants? I'm (still) dreaming of something like (sorry for the pseudo code):
```
#include "dilithium.h"
signature1=dilithium2(message);
signature2=dilithium4(message);
```
The way the PR presently builds things, it also exposes ref and avx2 entry points such as for library users to pick-and-chose what they want: Portability or performance. Ideally that should be hidden under the covers. 
But again, it depends on how you want the library to be used: As a 'code provider' for real libraries or as a real library in its own right: Please let me know when you'd have time for an in-person chat to talk this through: It'll have an impact on what cmake artefacts will be created.

**Comment by baentsch** [comment]
After performance testing showed no significant difference between `-mavx2`-built fips202.c, reverted the split between ref and avx2 variant. @gregorseiler Please review again.

**Pull request merged**
